# sleuth配置
spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.panda.entity.model
# Logger Config
logging:
  level:
    com.ydc.basepack.mapper: debug


