# sleuth配置
spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ydc.basepack.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      table-underline: true
      #mp2.3+ 全局表前缀 mp_
      #table-prefix: mp_
      #刷新mapper 调试神器
      #refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      # Sequence序列接口实现类配置
      #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.mybatisplus.core.handlers.MetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# Logger Config
logging:
  level:
    com.ydc.basepack.mapper: debug
    com.yukong.panda.common.base.mapper: debug



voice:
  app-id: 5f2d2373
  speaker: xiaoyan
  speed: 50
  volume:
  pitch:
  sample-rate:
  engine-type:
  tts-audio-path:
  local-url-prefix: ${user.dir}/voice/
  upload-url-prefix: https://test.aliyun.live.replay.sgcctop.com/voice/

upload:
  aliyun:
    oss:
      endpoint: shanghai.aliyuncs.com
      bucket-name: caster-dwtt
      access-key: LTAIjua1GgYCVlgf
      secret-access-key: hBgObWyBKoi8OIHrPBRss0yNhj91I1
      domain: shanghai.aliyuncs.com
  ftp:
    host: 119.45.104.69
    port: 21
    user: root
    password: root
    charset: utf-8
modify:
  sync-url: http://gateway.book.founderss.cn/book-review-api/api/doc/reviewTxtSync?phone=13524020573&secretKey=BEAB4F8870F7E2F990ED1F438D2A1411684D7F33B1D044208AAF3C34E910D76D7C177A326E1313BBAA2D5A94783EEF5A6CCBFC2ED9DE9B9E3EAED00A2D909528BDFA785740330337E63C6751D5AE71FE12C4F8EC21665A45327DB16EF0AF38A2BF7E45AA7EC8E51B73047363AFF7C1121E032EE2AAB0499B4D8ADE73E55D7F32
  async-url: http://gateway.book.founderss.cn/book-review-api/api/doc/reviewTxt?phone=13524020573&secretKey=BEAB4F8870F7E2F990ED1F438D2A1411684D7F33B1D044208AAF3C34E910D76D7C177A326E1313BBAA2D5A94783EEF5A6CCBFC2ED9DE9B9E3EAED00A2D909528BDFA785740330337E63C6751D5AE71FE12C4F8EC21665A45327DB16EF0AF38A2BF7E45AA7EC8E51B73047363AFF7C1121E032EE2AAB0499B4D8ADE73E55D7F32
  progress-url: http://gateway.book.founderss.cn/book-review-api/api/doc/review/result/{jobId}?phone=13524020573&secretKey=BEAB4F8870F7E2F990ED1F438D2A1411684D7F33B1D044208AAF3C34E910D76D7C177A326E1313BBAA2D5A94783EEF5A6CCBFC2ED9DE9B9E3EAED00A2D909528BDFA785740330337E63C6751D5AE71FE12C4F8EC21665A45327DB16EF0AF38A2BF7E45AA7EC8E51B73047363AFF7C1121E032EE2AAB0499B4D8ADE73E55D7F32
  res-url: http://gateway.book.founderss.cn/book-review-api/api/doc/review/getResultList/{jobId}?phone=13524020573&secretKey=BEAB4F8870F7E2F990ED1F438D2A1411684D7F33B1D044208AAF3C34E910D76D7C177A326E1313BBAA2D5A94783EEF5A6CCBFC2ED9DE9B9E3EAED00A2D909528BDFA785740330337E63C6751D5AE71FE12C4F8EC21665A45327DB16EF0AF38A2BF7E45AA7EC8E51B73047363AFF7C1121E032EE2AAB0499B4D8ADE73E55D7F32

write:
 appid: 174
 appSecret: 4be0fc61aa07158bd072f857353a6432
 platform: 1
 roleId:
 sign_type: MD5
 login_url: https://zs.giiso.com/oauth2/token/login.do